// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49DBQmBqsyt115kWfqArFiNAifsQXixE',
    appId: '1:144935331171:web:8f90897e5ae8e7e0b75f56',
    messagingSenderId: '144935331171',
    projectId: 'instagram-clone-88349owkdj',
    authDomain: 'instagram-clone-88349owkdj.firebaseapp.com',
    storageBucket: 'instagram-clone-88349owkdj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWURUQ2TVgGa-fKc0X_zaJdWyDEI-Gw6g',
    appId: '1:144935331171:android:827dcffc245060cbb75f56',
    messagingSenderId: '144935331171',
    projectId: 'instagram-clone-88349owkdj',
    storageBucket: 'instagram-clone-88349owkdj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC27d11E94emKaIYQ7uuoZnB1azGinYD9U',
    appId: '1:144935331171:ios:86f83607de0c0b1eb75f56',
    messagingSenderId: '144935331171',
    projectId: 'instagram-clone-88349owkdj',
    storageBucket: 'instagram-clone-88349owkdj.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC27d11E94emKaIYQ7uuoZnB1azGinYD9U',
    appId: '1:144935331171:ios:6b47e2593f974740b75f56',
    messagingSenderId: '144935331171',
    projectId: 'instagram-clone-88349owkdj',
    storageBucket: 'instagram-clone-88349owkdj.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
